CREATE TABLE "Balance" (
    "userId" TEXT NOT NULL,
    "usdAvailable" DOUBLE PRECISION NOT NULL DEFAULT 10000,
    "usdLocked" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "solAvailable" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "solLocked" DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT "Balance_pkey" PRIMARY KEY ("userId"),
    CONSTRAINT "Balance_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
